import type { MigrationInterface, QueryRunner } from 'typeorm';
export class CustomerManagement1725820800000 implements MigrationInterface {
  name = 'CustomerManagement1725820800000';
  async up(q: QueryRunner): Promise<void> {
    await q.query("ALTER TABLE customers ADD COLUMN lifecycle_status ENUM('NEW','ACTIVE','LOAN_PROCESSING','LOAN_APPROVED','LOAN_DISBURSED','LOAN_COMPLETED','INACTIVE') NOT NULL DEFAULT 'NEW', ADD COLUMN aadhaar_last_four VARCHAR(4) NULL, ADD COLUMN occupation VARCHAR(100) NULL, ADD COLUMN source_id CHAR(36) NULL, ADD COLUMN branch_id CHAR(36) NULL, ADD COLUMN preferred_product_id CHAR(36) NULL, ADD COLUMN requested_loan_amount DECIMAL(15,2) NULL, ADD COLUMN loan_tenure_months INT NULL, ADD COLUMN loan_purpose TEXT NULL, ADD COLUMN tags JSON NULL");
    await q.query('CREATE INDEX IDX_CUSTOMERS_LIFECYCLE_STATUS ON customers (lifecycle_status)');
    await q.query('CREATE INDEX IDX_CUSTOMERS_CITY ON customers (city)');
    await q.query('ALTER TABLE customers ADD CONSTRAINT FK_CUSTOMER_SOURCE FOREIGN KEY (source_id) REFERENCES lead_sources(id), ADD CONSTRAINT FK_CUSTOMER_BRANCH FOREIGN KEY (branch_id) REFERENCES branches(id), ADD CONSTRAINT FK_CUSTOMER_PREFERRED_PRODUCT FOREIGN KEY (preferred_product_id) REFERENCES loan_products(id)');
    await q.query("CREATE TABLE customer_activities (id CHAR(36) NOT NULL, customer_id CHAR(36) NOT NULL, type VARCHAR(50) NOT NULL, description TEXT NOT NULL, created_by_id CHAR(36) NULL, is_system TINYINT NOT NULL DEFAULT 0, metadata JSON NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), INDEX IDX_CUSTOMER_ACTIVITY_CUSTOMER (customer_id), CONSTRAINT FK_CUSTOMER_ACTIVITY_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers(id), CONSTRAINT FK_CUSTOMER_ACTIVITY_USER FOREIGN KEY (created_by_id) REFERENCES users(id))");
    await q.query("CREATE TABLE customer_notes (id CHAR(36) NOT NULL, customer_id CHAR(36) NOT NULL, note TEXT NOT NULL, created_by_id CHAR(36) NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), INDEX IDX_CUSTOMER_NOTE_CUSTOMER (customer_id), CONSTRAINT FK_CUSTOMER_NOTE_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers(id), CONSTRAINT FK_CUSTOMER_NOTE_USER FOREIGN KEY (created_by_id) REFERENCES users(id))");
    await q.query("CREATE TABLE customer_documents (id CHAR(36) NOT NULL, customer_id CHAR(36) NOT NULL, document_id CHAR(36) NOT NULL, document_type VARCHAR(80) NOT NULL, verification_status VARCHAR(30) NOT NULL DEFAULT 'PENDING', rejection_reason TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY UQ_CUSTOMER_DOCUMENT (customer_id, document_id), INDEX IDX_CUSTOMER_DOCUMENT_CUSTOMER (customer_id), CONSTRAINT FK_CUSTOMER_DOCUMENT_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers(id), CONSTRAINT FK_CUSTOMER_DOCUMENT_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents(id))");
  }
  async down(q: QueryRunner): Promise<void> { await q.query('DROP TABLE customer_documents'); await q.query('DROP TABLE customer_notes'); await q.query('DROP TABLE customer_activities'); await q.query('ALTER TABLE customers DROP FOREIGN KEY FK_CUSTOMER_SOURCE, DROP FOREIGN KEY FK_CUSTOMER_BRANCH, DROP FOREIGN KEY FK_CUSTOMER_PREFERRED_PRODUCT, DROP INDEX IDX_CUSTOMERS_LIFECYCLE_STATUS, DROP INDEX IDX_CUSTOMERS_CITY, DROP COLUMN lifecycle_status, DROP COLUMN aadhaar_last_four, DROP COLUMN occupation, DROP COLUMN source_id, DROP COLUMN branch_id, DROP COLUMN preferred_product_id, DROP COLUMN requested_loan_amount, DROP COLUMN loan_tenure_months, DROP COLUMN loan_purpose, DROP COLUMN tags'); }
}
