import type { MigrationInterface, QueryRunner } from 'typeorm';

export class ProductManagement1725993600000 implements MigrationInterface {
  name = 'ProductManagement1725993600000';
  async up(q: QueryRunner): Promise<void> {
    await q.query("ALTER TABLE loan_products ADD COLUMN description TEXT NULL, ADD COLUMN min_loan_amount DECIMAL(15,2) NULL, ADD COLUMN max_loan_amount DECIMAL(15,2) NULL, ADD COLUMN min_tenure_months INT NULL, ADD COLUMN max_tenure_months INT NULL, ADD COLUMN min_interest_rate DECIMAL(6,3) NULL, ADD COLUMN max_interest_rate DECIMAL(6,3) NULL, ADD COLUMN processing_fee DECIMAL(15,2) NULL, ADD COLUMN configuration JSON NULL");
    await q.query("ALTER TABLE lenders ADD COLUMN geography JSON NULL, ADD COLUMN notes TEXT NULL");
    await q.query("CREATE TABLE product_fields (id CHAR(36) NOT NULL, product_id CHAR(36) NOT NULL, field_key VARCHAR(80) NOT NULL, label VARCHAR(120) NOT NULL, field_type VARCHAR(30) NOT NULL, section VARCHAR(80) NULL, is_required TINYINT NOT NULL DEFAULT 0, options JSON NULL, validation JSON NULL, display_order INT NOT NULL DEFAULT 0, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY UQ_PRODUCT_FIELD (product_id, field_key), INDEX IDX_PRODUCT_FIELD_PRODUCT (product_id), CONSTRAINT FK_PRODUCT_FIELD_PRODUCT FOREIGN KEY (product_id) REFERENCES loan_products(id))");
    await q.query("CREATE TABLE product_workflow_stages (id CHAR(36) NOT NULL, product_id CHAR(36) NOT NULL, code VARCHAR(80) NOT NULL, name VARCHAR(120) NOT NULL, stage_order INT NOT NULL, is_active TINYINT NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), UNIQUE KEY UQ_PRODUCT_STAGE (product_id, code), INDEX IDX_PRODUCT_STAGE_PRODUCT (product_id), CONSTRAINT FK_PRODUCT_STAGE_PRODUCT FOREIGN KEY (product_id) REFERENCES loan_products(id))");
    await q.query("CREATE TABLE eligibility_rules (id CHAR(36) NOT NULL, product_id CHAR(36) NOT NULL, lender_id CHAR(36) NULL, rule_type VARCHAR(60) NOT NULL, operator VARCHAR(20) NOT NULL, rule_value JSON NOT NULL, value_type VARCHAR(30) NOT NULL DEFAULT 'number', priority INT NOT NULL DEFAULT 100, status ENUM('active','inactive') NOT NULL DEFAULT 'active', created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), INDEX IDX_ELIGIBILITY_RULE_PRODUCT (product_id), INDEX IDX_ELIGIBILITY_RULE_LENDER (lender_id), CONSTRAINT FK_ELIGIBILITY_RULE_PRODUCT FOREIGN KEY (product_id) REFERENCES loan_products(id), CONSTRAINT FK_ELIGIBILITY_RULE_LENDER FOREIGN KEY (lender_id) REFERENCES lenders(id))");
    await q.query("CREATE TABLE eligibility_results (id CHAR(36) NOT NULL, customer_id CHAR(36) NOT NULL, lead_id CHAR(36) NULL, product_id CHAR(36) NOT NULL, input JSON NOT NULL, recommendations JSON NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), INDEX IDX_ELIGIBILITY_RESULT_CUSTOMER (customer_id), INDEX IDX_ELIGIBILITY_RESULT_PRODUCT (product_id), CONSTRAINT FK_ELIGIBILITY_RESULT_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers(id), CONSTRAINT FK_ELIGIBILITY_RESULT_LEAD FOREIGN KEY (lead_id) REFERENCES leads(id), CONSTRAINT FK_ELIGIBILITY_RESULT_PRODUCT FOREIGN KEY (product_id) REFERENCES loan_products(id))");
    await q.query("CREATE TABLE document_links (id CHAR(36) NOT NULL, document_id CHAR(36) NOT NULL, customer_id CHAR(36) NULL, lead_id CHAR(36) NULL, application_id CHAR(36) NULL, product_id CHAR(36) NULL, document_type VARCHAR(100) NOT NULL, verified_by_id CHAR(36) NULL, verified_at DATETIME NULL, rejection_reason TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at DATETIME NULL, PRIMARY KEY (id), INDEX IDX_DOCUMENT_LINK_DOCUMENT (document_id), INDEX IDX_DOCUMENT_LINK_CUSTOMER (customer_id), INDEX IDX_DOCUMENT_LINK_LEAD (lead_id), CONSTRAINT FK_DOCUMENT_LINK_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents(id), CONSTRAINT FK_DOCUMENT_LINK_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers(id), CONSTRAINT FK_DOCUMENT_LINK_LEAD FOREIGN KEY (lead_id) REFERENCES leads(id), CONSTRAINT FK_DOCUMENT_LINK_APPLICATION FOREIGN KEY (application_id) REFERENCES loan_applications(id), CONSTRAINT FK_DOCUMENT_LINK_PRODUCT FOREIGN KEY (product_id) REFERENCES loan_products(id), CONSTRAINT FK_DOCUMENT_LINK_VERIFIER FOREIGN KEY (verified_by_id) REFERENCES users(id))");
    await q.query("CREATE TABLE document_versions (id CHAR(36) NOT NULL, document_id CHAR(36) NOT NULL, previous_document_id CHAR(36) NULL, version_number INT NOT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, PRIMARY KEY (id), INDEX IDX_DOCUMENT_VERSION_DOCUMENT (document_id), CONSTRAINT FK_DOCUMENT_VERSION_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents(id), CONSTRAINT FK_DOCUMENT_VERSION_PREVIOUS FOREIGN KEY (previous_document_id) REFERENCES documents(id))");
  }
  async down(q: QueryRunner): Promise<void> { await q.query('DROP TABLE document_versions'); await q.query('DROP TABLE document_links'); await q.query('DROP TABLE eligibility_results'); await q.query('DROP TABLE eligibility_rules'); await q.query('DROP TABLE product_workflow_stages'); await q.query('DROP TABLE product_fields'); await q.query('ALTER TABLE lenders DROP COLUMN geography, DROP COLUMN notes'); await q.query('ALTER TABLE loan_products DROP COLUMN description, DROP COLUMN min_loan_amount, DROP COLUMN max_loan_amount, DROP COLUMN min_tenure_months, DROP COLUMN max_tenure_months, DROP COLUMN min_interest_rate, DROP COLUMN max_interest_rate, DROP COLUMN processing_fee, DROP COLUMN configuration'); }
}
