import type { RequestHandler } from 'express';
import { z } from 'zod';
import { AppDataSource } from '../config/data-source';
import { Lender, LenderProduct, LoanProduct, ProductPolicy } from '../entities/crm.entities';
import { EligibilityRule, ProductField, ProductWorkflowStage } from '../entities/product-management.entities';
import { ProductCategory, RecordStatus } from '../constants/enums';
import { ensureBusinessIdSequenceAtLeast, nextBusinessId } from '../services/business-id.service';
import { evaluateEligibility, productDetail } from '../services/product-management.service';
import { AppError } from '../middleware/error-handler';

const productInput = z.object({ code: z.string().min(3).max(60).regex(/^[A-Z0-9_]+$/).optional(), name: z.string().min(3).optional(), category: z.nativeEnum(ProductCategory).optional(), status: z.nativeEnum(RecordStatus).optional(), metadata: z.record(z.unknown()).optional(), description: z.string().max(5000).optional(), minLoanAmount: z.coerce.number().nonnegative().optional(), maxLoanAmount: z.coerce.number().nonnegative().optional(), minTenureMonths: z.coerce.number().int().positive().optional(), maxTenureMonths: z.coerce.number().int().positive().optional(), minInterestRate: z.coerce.number().nonnegative().optional(), maxInterestRate: z.coerce.number().nonnegative().optional(), processingFee: z.coerce.number().nonnegative().optional(), configuration: z.record(z.unknown()).optional() });
const lenderInput = z.object({ code: z.string().min(3).max(50).regex(/^[A-Z0-9_]+$/).optional(), name: z.string().min(3).optional(), email: z.string().email().optional(), phone: z.string().max(30).optional(), minLoanAmount: z.coerce.number().nonnegative().optional(), maxLoanAmount: z.coerce.number().positive().optional(), status: z.nativeEnum(RecordStatus).optional(), geography: z.array(z.string().min(1)).max(100).optional(), notes: z.string().max(5000).optional() });
const decimals = (value: Record<string, unknown>) => Object.fromEntries(Object.entries(value).map(([key, data]) => ['minLoanAmount','maxLoanAmount','minInterestRate','maxInterestRate','processingFee'].includes(key) && typeof data === 'number' ? [key, data.toFixed(2)] : [key, data]));

export const listProducts: RequestHandler = async (req, res, next) => { try { const filters = z.object({ search: z.string().optional(), category: z.nativeEnum(ProductCategory).optional(), status: z.nativeEnum(RecordStatus).optional() }).parse(req.query); const query = AppDataSource.getRepository(LoanProduct).createQueryBuilder('product').orderBy('product.name', 'ASC'); if (filters.search) query.andWhere('(product.name LIKE :search OR product.code LIKE :search)', { search: `%${filters.search}%` }); if (filters.category) query.andWhere('product.category = :category', filters); if (filters.status) query.andWhere('product.status = :status', filters); res.json({ success: true, data: await query.getMany() }); } catch (error) { next(error); } };
export const getProduct: RequestHandler = async (req, res, next) => { try { res.json({ success: true, data: await productDetail(String(req.params.id)) }); } catch (error) { next(error); } };
export const createProduct: RequestHandler = async (req, res, next) => { try { const data = productInput.required({ code: true, name: true, category: true }).parse(req.body); const product = await AppDataSource.getRepository(LoanProduct).save({ ...decimals(data), status: data.status ?? RecordStatus.ACTIVE }); res.status(201).json({ success: true, data: product }); } catch (error) { next(error); } };
export const updateProduct: RequestHandler = async (req, res, next) => { try { const product = await AppDataSource.getRepository(LoanProduct).findOneBy({ id: String(req.params.id) }); if (!product) throw new AppError(404, 'Product not found'); Object.assign(product, decimals(productInput.parse(req.body))); await AppDataSource.getRepository(LoanProduct).save(product); res.json({ success: true, data: product }); } catch (error) { next(error); } };
export const setProductStatus: RequestHandler = async (req, res, next) => { try { const product = await AppDataSource.getRepository(LoanProduct).findOneBy({ id: String(req.params.id) }); if (!product) throw new AppError(404, 'Product not found'); product.status = z.object({ status: z.nativeEnum(RecordStatus) }).parse(req.body).status; await AppDataSource.getRepository(LoanProduct).save(product); res.json({ success: true, data: product }); } catch (error) { next(error); } };
export const listLenders: RequestHandler = async (_req, res) => res.json({ success: true, data: await AppDataSource.getRepository(Lender).find({ order: { name: 'ASC' } }) });
export const getLender: RequestHandler = async (req, res, next) => { try { const lender = await AppDataSource.getRepository(Lender).findOneBy({ id: String(req.params.id) }); if (!lender) throw new AppError(404, 'Lender not found'); const mappings = await AppDataSource.getRepository(LenderProduct).find({ where: { lenderId: lender.id }, relations: ['product'] }); res.json({ success: true, data: { ...lender, mappings } }); } catch (error) { next(error); } };
export const createLender: RequestHandler = async (req, res, next) => { try { const data = lenderInput.required({ code: true, name: true }).parse(req.body); const lender = await AppDataSource.transaction(async manager => {
  const latest = await manager.getRepository(Lender).createQueryBuilder('lender').withDeleted().select('lender.businessId', 'businessId').where('lender.businessId LIKE :prefix', { prefix: 'KUV-LENDER-%' }).orderBy('lender.businessId', 'DESC').getRawOne<{ businessId?: string }>();
  const lastValue = latest?.businessId?.match(/(\d+)$/)?.[1];
  if (lastValue) await ensureBusinessIdSequenceAtLeast(manager, 'lender', lastValue);
  return manager.getRepository(Lender).save({ ...decimals(data), businessId: await nextBusinessId(manager, 'lender'), status: data.status ?? RecordStatus.ACTIVE });
}); res.status(201).json({ success: true, data: lender }); } catch (error) { next(error); } };
export const updateLender: RequestHandler = async (req, res, next) => { try { const lender = await AppDataSource.getRepository(Lender).findOneBy({ id: String(req.params.id) }); if (!lender) throw new AppError(404, 'Lender not found'); Object.assign(lender, decimals(lenderInput.parse(req.body))); await AppDataSource.getRepository(Lender).save(lender); res.json({ success: true, data: lender }); } catch (error) { next(error); } };
export const mapLenderProduct: RequestHandler = async (req, res, next) => { try { const { productId, rules } = z.object({ productId: z.string().uuid(), rules: z.record(z.unknown()).default({}) }).parse(req.body); const lender = await AppDataSource.getRepository(Lender).findOneBy({ id: String(req.params.id) }); const product = await AppDataSource.getRepository(LoanProduct).findOneBy({ id: productId }); if (!lender || !product) throw new AppError(404, !lender ? 'Lender not found' : 'Product not found'); let mapping = await AppDataSource.getRepository(LenderProduct).findOneBy({ lenderId: lender.id, productId }); if (!mapping) mapping = await AppDataSource.getRepository(LenderProduct).save({ lenderId: lender.id, productId, status: RecordStatus.ACTIVE }); await AppDataSource.getRepository(ProductPolicy).save({ lenderProductId: mapping.id, name: 'Eligibility Policy', rules }); res.status(201).json({ success: true, data: mapping }); } catch (error) { next(error); } };

const fieldsInput = z.array(z.object({ fieldKey: z.string().regex(/^[a-zA-Z][a-zA-Z0-9_]*$/), label: z.string().min(1), fieldType: z.string().min(1), section: z.string().optional(), isRequired: z.boolean().optional(), options: z.array(z.unknown()).optional(), validation: z.record(z.unknown()).optional(), displayOrder: z.coerce.number().int().nonnegative(), status: z.nativeEnum(RecordStatus).optional() }));
export const getFields: RequestHandler = async (req, res, next) => { try { res.json({ success: true, data: await AppDataSource.getRepository(ProductField).find({ where: { productId: String(req.params.id), status: RecordStatus.ACTIVE }, order: { displayOrder: 'ASC' } }) }); } catch (error) { next(error); } };
export const replaceFields: RequestHandler = async (req, res, next) => { try { const productId = String(req.params.id); const fields = fieldsInput.parse(req.body.fields); if (!await AppDataSource.getRepository(LoanProduct).findOneBy({ id: productId })) throw new AppError(404, 'Product not found'); await AppDataSource.transaction(async manager => { await manager.getRepository(ProductField).delete({ productId }); await manager.getRepository(ProductField).save(fields.map(field => ({ ...field, productId, status: field.status ?? RecordStatus.ACTIVE }))); }); res.json({ success: true, data: await AppDataSource.getRepository(ProductField).find({ where: { productId }, order: { displayOrder: 'ASC' } }) }); } catch (error) { next(error); } };
const workflowInput = z.array(z.object({ code: z.string().min(1), name: z.string().min(1), stageOrder: z.coerce.number().int().nonnegative(), isActive: z.boolean().optional() }));
export const getWorkflow: RequestHandler = async (req, res, next) => { try { res.json({ success: true, data: await AppDataSource.getRepository(ProductWorkflowStage).find({ where: { productId: String(req.params.id) }, order: { stageOrder: 'ASC' } }) }); } catch (error) { next(error); } };
export const replaceWorkflow: RequestHandler = async (req, res, next) => { try { const productId = String(req.params.id); const stages = workflowInput.parse(req.body.stages); await AppDataSource.transaction(async manager => { await manager.getRepository(ProductWorkflowStage).delete({ productId }); await manager.getRepository(ProductWorkflowStage).save(stages.map(stage => ({ ...stage, productId, isActive: stage.isActive ?? true }))); }); res.json({ success: true, data: stages }); } catch (error) { next(error); } };
const ruleInput = z.object({ lenderId: z.string().uuid().optional(), ruleType: z.string().min(1), operator: z.enum(['GTE','LTE','EQ','IN']), ruleValue: z.unknown(), valueType: z.string().min(1).optional(), priority: z.coerce.number().int().nonnegative().optional(), status: z.nativeEnum(RecordStatus).optional() });
export const listRules: RequestHandler = async (req, res, next) => { try { res.json({ success: true, data: await AppDataSource.getRepository(EligibilityRule).find({ where: { productId: String(req.params.id) }, order: { priority: 'ASC' } }) }); } catch (error) { next(error); } };
export const createRule: RequestHandler = async (req, res, next) => { try { const input = ruleInput.parse(req.body); const rule = await AppDataSource.getRepository(EligibilityRule).save({ ...input, productId: String(req.params.id), valueType: input.valueType ?? 'number', priority: input.priority ?? 100, status: input.status ?? RecordStatus.ACTIVE }); res.status(201).json({ success: true, data: rule }); } catch (error) { next(error); } };
export const updateRule: RequestHandler = async (req, res, next) => { try { const rule = await AppDataSource.getRepository(EligibilityRule).findOneBy({ id: String(req.params.ruleId), productId: String(req.params.id) }); if (!rule) throw new AppError(404, 'Eligibility rule not found'); Object.assign(rule, ruleInput.partial().parse(req.body)); await AppDataSource.getRepository(EligibilityRule).save(rule); res.json({ success: true, data: rule }); } catch (error) { next(error); } };
export const evaluate: RequestHandler = async (req, res, next) => { try { const input = z.object({ customerId: z.string().uuid(), productId: z.string().uuid(), leadId: z.string().uuid().optional(), loanAmount: z.coerce.number().positive(), values: z.record(z.unknown()).optional() }).parse(req.body); res.json({ success: true, data: await evaluateEligibility(input) }); } catch (error) { next(error); } };
export const eligibilityCheck: RequestHandler = async (req, res, next) => { try { const input = z.object({ customerId: z.string().uuid(), productId: z.string().uuid(), loanAmount: z.coerce.number().positive(), values: z.record(z.unknown()).optional() }).parse(req.body); const result = await evaluateEligibility(input); res.json({ success: true, data: { ...result, matches: result.recommendations } }); } catch (error) { next(error); } };
