import type { RequestHandler } from 'express';
import { z } from 'zod';
import { AppDataSource } from '../config/data-source';
import { Customer, Lead, LeadSource, LoanProduct } from '../entities/crm.entities';
import { User } from '../entities/access.entities';
import { LeadStatus, RecordStatus } from '../constants/enums';
import { nextBusinessId } from '../services/business-id.service';
import { AppError } from '../middleware/error-handler';

const leadInput = z.object({ customerId: z.string().uuid(), sourceId: z.string().uuid().optional(), productId: z.string().uuid().optional(), assignedToId: z.string().uuid().optional(), requiredAmount: z.coerce.number().positive(), status: z.nativeEnum(LeadStatus).optional(), notes: z.string().max(3000).optional() });
const optionalUuid = z.preprocess(value => value === '' ? undefined : value, z.string().uuid().optional());
const optionalStatus = z.preprocess(value => value === '' ? undefined : value, z.nativeEnum(LeadStatus).optional());
const listInput = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20), search: z.string().optional(), status: optionalStatus, customerId: optionalUuid, sourceId: optionalUuid, productId: optionalUuid, assignedToId: optionalUuid });
async function validateReferences(data: z.infer<typeof leadInput>) { const customer = await AppDataSource.getRepository(Customer).findOneBy({ id: data.customerId }); if (!customer) throw new AppError(404, 'Customer not found'); if (data.sourceId && !await AppDataSource.getRepository(LeadSource).existsBy({ id: data.sourceId })) throw new AppError(400, 'Lead source not found'); if (data.productId && !await AppDataSource.getRepository(LoanProduct).existsBy({ id: data.productId })) throw new AppError(400, 'Loan product not found'); if (data.assignedToId) { const user = await AppDataSource.getRepository(User).findOneBy({ id: data.assignedToId }); if (!user || user.status !== RecordStatus.ACTIVE) throw new AppError(400, 'Assigned employee must be active'); } }
export const listLeads: RequestHandler = async (req, res, next) => { try { const q = listInput.parse(req.query); const qb = AppDataSource.getRepository(Lead).createQueryBuilder('lead').leftJoinAndSelect('lead.customer', 'customer').leftJoinAndSelect('lead.source', 'source').leftJoinAndSelect('lead.product', 'product').leftJoinAndSelect('lead.assignedTo', 'assignedTo'); if (q.search) qb.andWhere('(lead.business_id LIKE :search OR customer.full_name LIKE :search OR customer.mobile LIKE :search)', { search: `%${q.search}%` }); for (const [column, value] of Object.entries({ 'lead.status': q.status, 'lead.customer_id': q.customerId, 'lead.source_id': q.sourceId, 'lead.product_id': q.productId, 'lead.assigned_to_id': q.assignedToId })) if (value) qb.andWhere(`${column} = :${column.replace('.', '_')}`, { [column.replace('.', '_')]: value }); const [data, total] = await qb.orderBy('lead.createdAt', 'DESC').skip((q.page - 1) * q.limit).take(q.limit).getManyAndCount(); res.json({ success: true, data, pagination: { page: q.page, limit: q.limit, total, totalPages: Math.ceil(total / q.limit) } }); } catch (e) { next(e); } };
export const createLead: RequestHandler = async (req, res, next) => { try { const data = leadInput.parse(req.body); await validateReferences(data); const lead = await AppDataSource.transaction(async manager => manager.getRepository(Lead).save({ ...data, requiredAmount: data.requiredAmount.toFixed(2), businessId: await nextBusinessId(manager, 'lead'), snapshot: data.notes ? { notes: data.notes } : undefined })); res.status(201).json({ success: true, message: 'Lead created successfully', data: lead }); } catch (e) { next(e); } };
export const getLead: RequestHandler = async (req, res, next) => { try { const lead = await AppDataSource.getRepository(Lead).findOne({ where: { id: String(req.params.id) }, relations: ['customer', 'source', 'product', 'assignedTo'] }); if (!lead) throw new AppError(404, 'Lead not found'); res.json({ success: true, data: lead }); } catch (e) { next(e); } };
export const updateLead: RequestHandler = async (req, res, next) => { try { const data = leadInput.partial().parse(req.body); const lead = await AppDataSource.getRepository(Lead).findOneBy({ id: String(req.params.id) }); if (!lead) throw new AppError(404, 'Lead not found'); const candidate = { ...lead, ...data } as z.infer<typeof leadInput>; await validateReferences(candidate); Object.assign(lead, data, data.requiredAmount !== undefined ? { requiredAmount: data.requiredAmount.toFixed(2) } : {}, data.notes !== undefined ? { snapshot: { ...(lead.snapshot ?? {}), notes: data.notes } } : {}); await AppDataSource.getRepository(Lead).save(lead); res.json({ success: true, message: 'Lead updated successfully', data: lead }); } catch (e) { next(e); } };
export const assignLead: RequestHandler = async (req, res, next) => { try { const assignedToId = z.object({ assignedToId: z.string().uuid() }).parse(req.body).assignedToId; const lead = await AppDataSource.getRepository(Lead).findOneBy({ id: String(req.params.id) }); if (!lead) throw new AppError(404, 'Lead not found'); await validateReferences({ ...lead, assignedToId, requiredAmount: Number(lead.requiredAmount) } as z.infer<typeof leadInput>); lead.assignedToId = assignedToId; lead.status = LeadStatus.ASSIGNED; await AppDataSource.getRepository(Lead).save(lead); res.json({ success: true, message: 'Lead assigned successfully', data: lead }); } catch (e) { next(e); } };
export const updateLeadStatus: RequestHandler = async (req, res, next) => { try { const status = z.object({ status: z.nativeEnum(LeadStatus) }).parse(req.body).status; const lead = await AppDataSource.getRepository(Lead).findOneBy({ id: String(req.params.id) }); if (!lead) throw new AppError(404, 'Lead not found'); lead.status = status; await AppDataSource.getRepository(Lead).save(lead); res.json({ success: true, message: 'Lead status updated successfully', data: lead }); } catch (e) { next(e); } };
export const referenceData: RequestHandler = async (_req, res) => res.json({ success: true, data: { customers: await AppDataSource.getRepository(Customer).find({ select: ['id', 'businessId', 'fullName', 'mobile'], order: { fullName: 'ASC' } }), users: await AppDataSource.getRepository(User).find({ where: { status: RecordStatus.ACTIVE }, select: ['id', 'firstName', 'lastName', 'email'] }), products: await AppDataSource.getRepository(LoanProduct).find({ where: { status: RecordStatus.ACTIVE }, order: { name: 'ASC' } }), leadSources: await AppDataSource.getRepository(LeadSource).find({ where: { status: RecordStatus.ACTIVE }, order: { name: 'ASC' } }) } });
