import type { RequestHandler } from 'express';
import { z } from 'zod';
import { AppDataSource } from '../config/data-source';
import { Branch, User } from '../entities/access.entities';
import { CustomerActivity, CustomerDocument, CustomerNote } from '../entities/customer-management.entities';
import { Customer, LeadSource, LoanProduct } from '../entities/crm.entities';
import { Disbursement, LoanApplication } from '../entities/lifecycle.entities';
import { AuditLog } from '../entities/work-finance.entities';
import { ApplicationStatus, AuditAction, CustomerLifecycleStatus, DisbursementStatus, RecordStatus } from '../constants/enums';
import { AppError } from '../middleware/error-handler';
import { nextBusinessId } from '../services/business-id.service';
import { decryptField, encryptField, maskSensitive } from '../utils/field-crypto';
const statuses = Object.values(CustomerLifecycleStatus);
const input = z.object({ fullName: z.string().min(2).max(180), mobile: z.string().min(8).max(20), alternateMobile: z.string().max(20).optional(), email: z.string().email().optional(), dob: z.string().optional(), gender: z.string().max(30).optional(), pan: z.string().min(10).max(20).optional(), aadhaarLastFour: z.string().regex(/^\d{4}$/).optional(), aadhaarStatus: z.string().max(40).optional(), occupation: z.string().max(100).optional(), employmentType: z.string().max(50).optional(), monthlyIncome: z.coerce.number().nonnegative().optional(), addressLine: z.string().max(2000).optional(), city: z.string().max(100).optional(), state: z.string().max(100).optional(), pincode: z.string().max(12).optional(), sourceId: z.string().uuid().optional(), branchId: z.string().uuid().optional(), assignedRmId: z.string().uuid().optional(), preferredProductId: z.string().uuid().optional(), requestedLoanAmount: z.coerce.number().nonnegative().optional(), loanTenureMonths: z.coerce.number().int().positive().max(600).optional(), loanPurpose: z.string().max(1000).optional(), tags: z.array(z.string().max(40)).max(20).optional(), lifecycleStatus: z.enum(statuses as [string, ...string[]]).optional() });
const normalizeMobile = (value: string) => value.replace(/\D/g, '');
const safeCustomer = (customer: Customer) => {
  let pan: string | null = null;
  if (customer.panEncrypted) {
    try { pan = maskSensitive(decryptField(customer.panEncrypted)); } catch { pan = null; }
  }
  return { ...customer, pan, panEncrypted: undefined, aadhaar: customer.aadhaarLastFour ? `XXXX XXXX ${customer.aadhaarLastFour}` : null };
};
async function audit(userId: string | undefined, action: AuditAction, customerId: string, changed: Record<string, unknown>) { await AppDataSource.getRepository(AuditLog).save({ userId, action, module: 'customers', entityType: 'Customer', entityId: customerId, newValue: changed }); }
async function activity(customerId: string, type: string, description: string, createdById?: string, isSystem = true) { await AppDataSource.getRepository(CustomerActivity).save({ customerId, type, description, createdById, isSystem }); }
async function validateAssignment(branchId?: string, userId?: string) { if (!userId) return; if (!branchId) throw new AppError(400, 'A branch is required when assigning an employee'); const user = await AppDataSource.getRepository(User).findOneBy({ id: userId }); if (!user || user.status !== RecordStatus.ACTIVE || user.branchId !== branchId) throw new AppError(400, 'Assigned employee must be active and belong to the selected branch'); }
async function duplicateCheck(mobile: string, email?: string, excludeId?: string) { const query = AppDataSource.getRepository(Customer).createQueryBuilder('customer').where('REPLACE(REPLACE(REPLACE(customer.mobile, \'-\', \'\'), \' \', \'\'), \'+\', \'\') = :mobile', { mobile: normalizeMobile(mobile) }).andWhere('customer.lifecycle_status != :inactive', { inactive: CustomerLifecycleStatus.INACTIVE }).andWhere('customer.deleted_at IS NULL'); if (excludeId) query.andWhere('customer.id != :excludeId', { excludeId }); if (await query.getOne()) throw new AppError(409, 'A customer with this mobile number already exists'); if (email) { const emailQuery = AppDataSource.getRepository(Customer).createQueryBuilder('customer').where('LOWER(customer.email) = :email', { email: email.toLowerCase() }).andWhere('customer.lifecycle_status != :inactive', { inactive: CustomerLifecycleStatus.INACTIVE }).andWhere('customer.deleted_at IS NULL'); if (excludeId) emailQuery.andWhere('customer.id != :excludeId', { excludeId }); if (await emailQuery.getOne()) throw new AppError(409, 'A customer with this email already exists'); } }
const decimal = (value?: number) => value === undefined ? undefined : value.toFixed(2);
export const listCustomers: RequestHandler = async (req, res, next) => { try { const query = z.object({ page: z.coerce.number().int().min(1).default(1), limit: z.coerce.number().int().min(1).max(100).default(20), search: z.string().optional(), lifecycleStatus: z.enum(statuses as [string, ...string[]]).optional(), city: z.string().optional(), assignedRmId: z.string().uuid().optional(), sourceId: z.string().uuid().optional(), loanTypeId: z.string().uuid().optional(), createdFrom: z.string().date().optional(), createdTo: z.string().date().optional(), minAmount: z.coerce.number().nonnegative().optional(), maxAmount: z.coerce.number().nonnegative().optional() }).parse(req.query); const qb = AppDataSource.getRepository(Customer).createQueryBuilder('customer').leftJoinAndSelect('customer.assignedRm', 'assignedRm').leftJoinAndSelect('customer.branch', 'branch').leftJoinAndSelect('customer.source', 'source'); if (query.search) qb.andWhere('(customer.full_name LIKE :search OR customer.business_id LIKE :search OR customer.mobile LIKE :search OR customer.email LIKE :search)', { search: `%${query.search}%` }); if (query.lifecycleStatus) qb.andWhere('customer.lifecycle_status = :status', { status: query.lifecycleStatus }); if (query.city) qb.andWhere('customer.city = :city', { city: query.city }); if (query.assignedRmId) qb.andWhere('customer.assigned_rm_id = :assignedRmId', { assignedRmId: query.assignedRmId }); if (query.sourceId) qb.andWhere('customer.source_id = :sourceId', { sourceId: query.sourceId }); if (query.loanTypeId) qb.andWhere('customer.preferred_product_id = :loanTypeId', { loanTypeId: query.loanTypeId }); if (query.createdFrom) qb.andWhere('customer.created_at >= :createdFrom', { createdFrom: query.createdFrom }); if (query.createdTo) qb.andWhere('customer.created_at < DATE_ADD(:createdTo, INTERVAL 1 DAY)', { createdTo: query.createdTo }); if (query.minAmount !== undefined) qb.andWhere('customer.requested_loan_amount >= :minAmount', { minAmount: query.minAmount }); if (query.maxAmount !== undefined) qb.andWhere('customer.requested_loan_amount <= :maxAmount', { maxAmount: query.maxAmount }); const [data, total] = await qb.orderBy('customer.createdAt', 'DESC').skip((query.page - 1) * query.limit).take(query.limit).getManyAndCount(); res.json({ success: true, data: data.map(safeCustomer), pagination: { page: query.page, limit: query.limit, total, totalPages: Math.ceil(total / query.limit) } }); } catch (error) { next(error); } };
export const customerStats: RequestHandler = async (_req, res, next) => { try { const rows = await AppDataSource.getRepository(Customer).createQueryBuilder('customer').select('customer.lifecycle_status', 'status').addSelect('COUNT(*)', 'count').groupBy('customer.lifecycle_status').getRawMany<{ status: CustomerLifecycleStatus; count: string }>(); const count = (status: CustomerLifecycleStatus) => Number(rows.find(row => row.status === status)?.count ?? 0); res.json({ success: true, data: { total: rows.reduce((sum, row) => sum + Number(row.count), 0), active: count(CustomerLifecycleStatus.ACTIVE), new: count(CustomerLifecycleStatus.NEW), loanProcessing: count(CustomerLifecycleStatus.LOAN_PROCESSING), loanDisbursed: count(CustomerLifecycleStatus.LOAN_DISBURSED), loanCompleted: count(CustomerLifecycleStatus.LOAN_COMPLETED) } }); } catch (error) { next(error); } };
export const createCustomer: RequestHandler = async (req, res, next) => { try { const data = input.parse(req.body); await duplicateCheck(data.mobile, data.email); await validateAssignment(data.branchId, data.assignedRmId); const { pan, ...fields } = data; const customer = await AppDataSource.transaction(async manager => { const repository = manager.getRepository(Customer); return repository.save(repository.create({ ...fields, email: data.email?.toLowerCase(), panEncrypted: encryptField(pan) ?? undefined, monthlyIncome: decimal(data.monthlyIncome), requestedLoanAmount: decimal(data.requestedLoanAmount), lifecycleStatus: (data.lifecycleStatus ?? CustomerLifecycleStatus.NEW) as CustomerLifecycleStatus, businessId: await nextBusinessId(manager, 'customer') })); }); await activity(customer.id, 'CUSTOMER_CREATED', 'Customer profile created', req.auth?.id); await audit(req.auth?.id, AuditAction.CREATE, customer.id, { lifecycleStatus: customer.lifecycleStatus }); res.status(201).json({ success: true, message: 'Customer created successfully', data: safeCustomer(customer) }); } catch (error) { next(error); } };
export const updateCustomer: RequestHandler = async (req, res, next) => { try { const data = input.partial().parse(req.body); const customer = await AppDataSource.getRepository(Customer).findOne({ where: { id: String(req.params.id) }, select: ['id', 'mobile', 'email', 'panEncrypted', 'branchId', 'assignedRmId', 'lifecycleStatus'] }); if (!customer) throw new AppError(404, 'Customer not found'); if (data.mobile || data.email) await duplicateCheck(data.mobile ?? customer.mobile, data.email ?? customer.email, customer.id); const branchId = data.branchId ?? customer.branchId; const assignedRmId = data.assignedRmId ?? customer.assignedRmId; await validateAssignment(branchId, assignedRmId); const { pan, ...fields } = data; Object.assign(customer, fields, { email: data.email?.toLowerCase(), ...(pan ? { panEncrypted: encryptField(pan) ?? undefined } : {}), monthlyIncome: decimal(data.monthlyIncome), requestedLoanAmount: decimal(data.requestedLoanAmount) }); await AppDataSource.getRepository(Customer).save(customer); await activity(customer.id, 'CUSTOMER_UPDATED', 'Customer profile updated', req.auth?.id); await audit(req.auth?.id, AuditAction.UPDATE, customer.id, { changedFields: Object.keys(data).filter(key => !['pan', 'aadhaarLastFour'].includes(key)) }); res.json({ success: true, message: 'Customer updated successfully', data: safeCustomer(customer) }); } catch (error) { next(error); } };
export const deactivateCustomer: RequestHandler = async (req, res, next) => { try { const customer = await AppDataSource.getRepository(Customer).findOneBy({ id: String(req.params.id) }); if (!customer) throw new AppError(404, 'Customer not found'); customer.lifecycleStatus = CustomerLifecycleStatus.INACTIVE; await AppDataSource.getRepository(Customer).save(customer); await activity(customer.id, 'CUSTOMER_DEACTIVATED', 'Customer deactivated', req.auth?.id); await audit(req.auth?.id, AuditAction.DELETE, customer.id, { lifecycleStatus: CustomerLifecycleStatus.INACTIVE }); res.json({ success: true, message: 'Customer deactivated successfully' }); } catch (error) { next(error); } };
export const getCustomer: RequestHandler = async (req, res, next) => { try { const id = String(req.params.id); const customer = await AppDataSource.getRepository(Customer).findOne({ where: { id }, relations: ['assignedRm', 'branch', 'source', 'preferredProduct'] }); if (!customer) throw new AppError(404, 'Customer not found'); const loans = await AppDataSource.getRepository(LoanApplication).find({ where: { customerId: id }, relations: ['product', 'lender'], order: { createdAt: 'DESC' } }); const disbursements = loans.length ? await AppDataSource.getRepository(Disbursement).createQueryBuilder('disbursement').where('disbursement.application_id IN (:...ids)', { ids: loans.map(loan => loan.id) }).andWhere('disbursement.status IN (:...statuses)', { statuses: [DisbursementStatus.PART_DISBURSED, DisbursementStatus.FULLY_DISBURSED] }).getMany() : []; const active = loans.filter(loan => ![ApplicationStatus.DRAFT, ApplicationStatus.REJECTED, ApplicationStatus.WITHDRAWN, ApplicationStatus.CLOSED].includes(loan.status)); const approvedStatuses = [ApplicationStatus.SANCTIONED, ApplicationStatus.DOCUMENTATION, ApplicationStatus.DISBURSEMENT_PENDING, ApplicationStatus.PART_DISBURSED, ApplicationStatus.FULLY_DISBURSED, ApplicationStatus.CLOSED]; const summary = { totalLoans: loans.length, activeLoans: active.length, completedLoans: loans.filter(loan => loan.status === ApplicationStatus.CLOSED).length, requestedAmount: loans.filter(loan => loan.status !== ApplicationStatus.WITHDRAWN).reduce((sum, loan) => sum + Number(loan.requestedAmount), 0), approvedAmount: loans.filter(loan => approvedStatuses.includes(loan.status)).reduce((sum, loan) => sum + Number(loan.approvedAmount ?? 0), 0), rejectedAmount: loans.filter(loan => loan.status === ApplicationStatus.REJECTED).reduce((sum, loan) => sum + Number(loan.requestedAmount), 0), rejectedLoans: loans.filter(loan => loan.status === ApplicationStatus.REJECTED).length, disbursedAmount: disbursements.reduce((sum, item) => sum + Number(item.amount), 0) }; res.json({ success: true, data: { customer: safeCustomer(customer), loanSummary: summary, loans } }); } catch (error) { next(error); } };
export const listCustomerLoans: RequestHandler = async (req, res, next) => { try { const customerId = String(req.params.id); if (!await AppDataSource.getRepository(Customer).existsBy({ id: customerId })) throw new AppError(404, 'Customer not found'); const loans = await AppDataSource.getRepository(LoanApplication).find({ where: { customerId }, relations: ['product', 'lender'], order: { createdAt: 'DESC' } }); res.json({ success: true, data: loans }); } catch (error) { next(error); } };
export const listActivities: RequestHandler = async (req, res, next) => { try { const data = await AppDataSource.getRepository(CustomerActivity).find({ where: { customerId: String(req.params.id) }, relations: ['createdBy'], order: { createdAt: 'DESC' } }); res.json({ success: true, data }); } catch (error) { next(error); } };
export const addActivity: RequestHandler = async (req, res, next) => { try { const data = z.object({ type: z.enum(['CALL', 'WHATSAPP', 'EMAIL', 'MEETING', 'NOTE']), description: z.string().min(2).max(2000) }).parse(req.body); const customerId = String(req.params.id); if (!await AppDataSource.getRepository(Customer).existsBy({ id: customerId })) throw new AppError(404, 'Customer not found'); const record = await AppDataSource.getRepository(CustomerActivity).save({ customerId, ...data, createdById: req.auth?.id, isSystem: false }); res.status(201).json({ success: true, data: record }); } catch (error) { next(error); } };
export const listNotes: RequestHandler = async (req, res, next) => { try { const data = await AppDataSource.getRepository(CustomerNote).find({ where: { customerId: String(req.params.id) }, relations: ['createdBy'], order: { createdAt: 'DESC' } }); res.json({ success: true, data }); } catch (error) { next(error); } };
export const addNote: RequestHandler = async (req, res, next) => { try { const note = z.object({ note: z.string().min(2).max(5000) }).parse(req.body).note; const customerId = String(req.params.id); if (!await AppDataSource.getRepository(Customer).existsBy({ id: customerId })) throw new AppError(404, 'Customer not found'); const record = await AppDataSource.getRepository(CustomerNote).save({ customerId, note, createdById: req.auth?.id }); await activity(customerId, 'NOTE', 'Internal note added', req.auth?.id, false); res.status(201).json({ success: true, data: record }); } catch (error) { next(error); } };
export const listDocuments: RequestHandler = async (req, res, next) => { try { const data = await AppDataSource.getRepository(CustomerDocument).find({ where: { customerId: String(req.params.id) }, relations: ['document', 'document.uploadedBy'], order: { createdAt: 'DESC' } }); res.json({ success: true, data }); } catch (error) { next(error); } };
export const setLifecycleStatus: RequestHandler = async (req, res, next) => { try { const lifecycleStatus = z.object({ lifecycleStatus: z.enum(statuses as [string, ...string[]]) }).parse(req.body).lifecycleStatus as CustomerLifecycleStatus; const customer = await AppDataSource.getRepository(Customer).findOneBy({ id: String(req.params.id) }); if (!customer) throw new AppError(404, 'Customer not found'); customer.lifecycleStatus = lifecycleStatus; await AppDataSource.getRepository(Customer).save(customer); await activity(customer.id, 'STATUS_CHANGED', `Customer lifecycle changed to ${lifecycleStatus}`, req.auth?.id); await audit(req.auth?.id, AuditAction.STATUS_CHANGE, customer.id, { lifecycleStatus }); res.json({ success: true, data: safeCustomer(customer) }); } catch (error) { next(error); } };
export const assignCustomer: RequestHandler = async (req, res, next) => { try { const { branchId, assignedRmId } = z.object({ branchId: z.string().uuid(), assignedRmId: z.string().uuid() }).parse(req.body); await validateAssignment(branchId, assignedRmId); const customer = await AppDataSource.getRepository(Customer).findOneBy({ id: String(req.params.id) }); if (!customer) throw new AppError(404, 'Customer not found'); customer.branchId = branchId; customer.assignedRmId = assignedRmId; await AppDataSource.getRepository(Customer).save(customer); await activity(customer.id, 'ASSIGNED', 'Customer assignment updated', req.auth?.id); await audit(req.auth?.id, AuditAction.ASSIGN, customer.id, { branchId, assignedRmId }); res.json({ success: true, data: safeCustomer(customer) }); } catch (error) { next(error); } };
export const customerReferenceData: RequestHandler = async (_req, res) => res.json({ success: true, data: { branches: await AppDataSource.getRepository(Branch).find({ where: { status: RecordStatus.ACTIVE } }), users: await AppDataSource.getRepository(User).find({ where: { status: RecordStatus.ACTIVE }, select: ['id', 'firstName', 'lastName', 'email', 'branchId'] }), sources: await AppDataSource.getRepository(LeadSource).find({ where: { status: RecordStatus.ACTIVE } }), products: await AppDataSource.getRepository(LoanProduct).find({ where: { status: RecordStatus.ACTIVE } }) } });
