import { Router } from 'express';
import multer from 'multer';
import * as controller from '../controllers/catalog.controller';
import * as documents from '../controllers/document.controller';
import { env } from '../config/env';
import { authenticate, requirePermission } from '../middleware/auth.middleware';

export const catalogRouter = Router();
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.DOCUMENT_MAX_SIZE_MB * 1024 * 1024 } });
catalogRouter.use(authenticate);
catalogRouter.get('/products', requirePermission('products.manage'), controller.listProducts);
catalogRouter.post('/products', requirePermission('products.manage'), controller.createProduct);
catalogRouter.get('/products/:id', requirePermission('products.manage'), controller.getProduct);
catalogRouter.put('/products/:id', requirePermission('products.manage'), controller.updateProduct);
catalogRouter.patch('/products/:id', requirePermission('products.manage'), controller.updateProduct);
catalogRouter.patch('/products/:id/status', requirePermission('products.manage'), controller.setProductStatus);
catalogRouter.get('/products/:id/fields', requirePermission('leads.create'), controller.getFields);
catalogRouter.put('/products/:id/fields', requirePermission('products.manage'), controller.replaceFields);
catalogRouter.get('/products/:id/workflow', requirePermission('products.manage'), controller.getWorkflow);
catalogRouter.put('/products/:id/workflow', requirePermission('products.manage'), controller.replaceWorkflow);
catalogRouter.get('/products/:id/rules', requirePermission('products.manage'), controller.listRules);
catalogRouter.post('/products/:id/rules', requirePermission('products.manage'), controller.createRule);
catalogRouter.patch('/products/:id/rules/:ruleId', requirePermission('products.manage'), controller.updateRule);
catalogRouter.get('/lenders', requirePermission('lenders.manage'), controller.listLenders);
catalogRouter.post('/lenders', requirePermission('lenders.manage'), controller.createLender);
catalogRouter.get('/lenders/:id', requirePermission('lenders.manage'), controller.getLender);
catalogRouter.put('/lenders/:id', requirePermission('lenders.manage'), controller.updateLender);
catalogRouter.patch('/lenders/:id', requirePermission('lenders.manage'), controller.updateLender);
catalogRouter.post('/lenders/:id/products', requirePermission('lenders.manage'), controller.mapLenderProduct);
catalogRouter.post('/eligibility/check', requirePermission('leads.update'), controller.eligibilityCheck);
catalogRouter.post('/eligibility/evaluate', requirePermission('leads.update'), controller.evaluate);
catalogRouter.get('/documents', requirePermission('documents.view'), documents.list);
catalogRouter.get('/documents/reference-data', requirePermission('documents.upload'), documents.referenceData);
catalogRouter.post('/documents/upload', requirePermission('documents.upload'), upload.single('file'), documents.upload);
catalogRouter.get('/documents/:id/download', requirePermission('documents.view'), documents.download);
catalogRouter.get('/documents/:id/versions', requirePermission('documents.view'), documents.history);
catalogRouter.post('/documents/:id/verify', requirePermission('documents.verify'), documents.verify);
catalogRouter.post('/documents/:id/reject', requirePermission('documents.verify'), documents.reject);
