import { Router } from "express";
import * as controller from "../controllers/crm.controller";
import * as customers from "../controllers/customer.controller";
import { authenticate, requirePermission } from "../middleware/auth.middleware";
export const crmRouter = Router();
crmRouter.use(authenticate);
crmRouter.get(
  "/customer-reference-data",
  requirePermission("customers.view"),
  customers.customerReferenceData,
);
crmRouter.get(
  "/customers/stats",
  requirePermission("customers.view"),
  customers.customerStats,
);
crmRouter.get(
  "/customers",
  requirePermission("customers.view"),
  customers.listCustomers,
);
crmRouter.post(
  "/customers",
  requirePermission("customers.create"),
  customers.createCustomer,
);
crmRouter.get(
  "/customers/:id/loans",
  requirePermission("customers.view"),
  customers.listCustomerLoans,
);
crmRouter.get(
  "/customers/:id/documents",
  requirePermission("customers.view"),
  customers.listDocuments,
);
crmRouter.get(
  "/customers/:id/activities",
  requirePermission("customers.view"),
  customers.listActivities,
);
crmRouter.post(
  "/customers/:id/activities",
  requirePermission("customers.update"),
  customers.addActivity,
);
crmRouter.get(
  "/customers/:id/notes",
  requirePermission("customers.view"),
  customers.listNotes,
);
crmRouter.post(
  "/customers/:id/notes",
  requirePermission("customers.update"),
  customers.addNote,
);
crmRouter.patch(
  "/customers/:id/status",
  requirePermission("customers.update"),
  customers.setLifecycleStatus,
);
crmRouter.patch(
  "/customers/:id/assign",
  requirePermission("customers.update"),
  customers.assignCustomer,
);
crmRouter.get(
  "/customers/:id",
  requirePermission("customers.view"),
  customers.getCustomer,
);
crmRouter.put(
  "/customers/:id",
  requirePermission("customers.update"),
  customers.updateCustomer,
);
crmRouter.delete(
  "/customers/:id",
  requirePermission("customers.delete"),
  customers.deactivateCustomer,
);
crmRouter.get(
  "/reference-data",
  requirePermission("leads.create"),
  controller.referenceData,
);
crmRouter.get("/leads", requirePermission("leads.view"), controller.listLeads);
crmRouter.post(
  "/leads",
  requirePermission("leads.create"),
  controller.createLead,
);
crmRouter.get(
  "/leads/:id",
  requirePermission("leads.view"),
  controller.getLead,
);
crmRouter.put(
  "/leads/:id",
  requirePermission("leads.update"),
  controller.updateLead,
);
crmRouter.post(
  "/leads/:id/assign",
  requirePermission("leads.assign"),
  controller.assignLead,
);
crmRouter.post(
  "/leads/:id/status",
  requirePermission("leads.update"),
  controller.updateLeadStatus,
);
