import { Column, Entity, Index, JoinColumn, ManyToOne, Unique } from 'typeorm';
import { AuditAction, PaymentStatus, Priority, RecordStatus, TaskStatus } from '../constants/enums';
import { SoftDeleteEntity, UuidEntity } from './base.entity';
import { User } from './access.entities';
import { Customer, Lead, Lender, LoanProduct } from './crm.entities';
import { Disbursement, LoanApplication } from './lifecycle.entities';
@Entity('tasks') export class Task extends SoftDeleteEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ length: 180 }) title!: string; @Column({ type: 'text', nullable: true }) description?: string; @Index() @Column({ name: 'assigned_to_id', type: 'char', length: 36, nullable: true }) assignedToId?: string; @Column({ name: 'customer_id', type: 'char', length: 36, nullable: true }) customerId?: string; @Column({ name: 'lead_id', type: 'char', length: 36, nullable: true }) leadId?: string; @Column({ name: 'application_id', type: 'char', length: 36, nullable: true }) applicationId?: string; @Index() @Column({ name: 'due_date', type: 'datetime', nullable: true }) dueDate?: Date; @Column({ type: 'enum', enum: Priority, default: Priority.MEDIUM }) priority!: Priority; @Column({ type: 'enum', enum: TaskStatus, default: TaskStatus.PENDING }) status!: TaskStatus; @Column({ name: 'completed_at', type: 'datetime', nullable: true }) completedAt?: Date; @ManyToOne(() => User) @JoinColumn({ name: 'assigned_to_id' }) assignedTo?: User; }
@Entity('follow_ups') export class FollowUp extends SoftDeleteEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ name: 'customer_id', type: 'char', length: 36, nullable: true }) customerId?: string; @Column({ name: 'lead_id', type: 'char', length: 36, nullable: true }) leadId?: string; @Column({ name: 'application_id', type: 'char', length: 36, nullable: true }) applicationId?: string; @Column({ name: 'scheduled_at', type: 'datetime' }) scheduledAt!: Date; @Column({ length: 50 }) channel!: string; @Column({ type: 'text', nullable: true }) notes?: string; @Column({ name: 'completed_at', type: 'datetime', nullable: true }) completedAt?: Date; }
@Entity('communications') export class Communication extends SoftDeleteEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ name: 'customer_id', type: 'char', length: 36, nullable: true }) customerId?: string; @Column({ name: 'lead_id', type: 'char', length: 36, nullable: true }) leadId?: string; @Column({ name: 'application_id', type: 'char', length: 36, nullable: true }) applicationId?: string; @Column({ name: 'created_by_id', type: 'char', length: 36, nullable: true }) createdById?: string; @Column({ length: 50 }) channel!: string; @Column({ type: 'text' }) content!: string; @Column({ name: 'occurred_at', type: 'datetime' }) occurredAt!: Date; }
@Entity('notifications') export class Notification extends SoftDeleteEntity { @Index() @Column({ name: 'user_id', type: 'char', length: 36 }) userId!: string; @Column({ length: 180 }) title!: string; @Column({ type: 'text' }) body!: string; @Column({ name: 'is_read', default: false }) isRead!: boolean; @Column({ name: 'read_at', type: 'datetime', nullable: true }) readAt?: Date; @ManyToOne(() => User) @JoinColumn({ name: 'user_id' }) user!: User; }
@Entity('audit_logs') export class AuditLog extends UuidEntity { @Index() @Column({ name: 'user_id', type: 'char', length: 36, nullable: true }) userId?: string; @Index() @Column({ type: 'enum', enum: AuditAction }) action!: AuditAction; @Index() @Column({ length: 80 }) module!: string; @Column({ name: 'entity_type', length: 80 }) entityType!: string; @Index() @Column({ name: 'entity_id', type: 'char', length: 36, nullable: true }) entityId?: string; @Column({ name: 'old_value', type: 'json', nullable: true }) oldValue?: Record<string, unknown>; @Column({ name: 'new_value', type: 'json', nullable: true }) newValue?: Record<string, unknown>; @Column({ name: 'ip_address', length: 64, nullable: true }) ipAddress?: string; @Column({ name: 'user_agent', type: 'text', nullable: true }) userAgent?: string; }
@Entity('dsa_partners') export class DsaPartner extends SoftDeleteEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ length: 180 }) name!: string; @Column({ length: 180, nullable: true }) company?: string; @Column({ length: 20 }) mobile!: string; @Column({ length: 180, nullable: true }) email?: string; @Column({ length: 100, nullable: true }) city?: string; @Column({ name: 'pan_encrypted', type: 'text', nullable: true }) panEncrypted?: string; @Column({ name: 'bank_details_encrypted', type: 'text', nullable: true }) bankDetailsEncrypted?: string; @Column({ name: 'assigned_rm_id', type: 'char', length: 36, nullable: true }) assignedRmId?: string; @Column({ type: 'enum', enum: RecordStatus, default: RecordStatus.ACTIVE }) status!: RecordStatus; @ManyToOne(() => User) @JoinColumn({ name: 'assigned_rm_id' }) assignedRm?: User; }
@Entity('sub_dsas') export class SubDsa extends SoftDeleteEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ name: 'partner_id', type: 'char', length: 36 }) partnerId!: string; @Column({ length: 180 }) name!: string; @Column({ length: 20 }) mobile!: string; @Column({ length: 180, nullable: true }) email?: string; @Column({ type: 'enum', enum: RecordStatus, default: RecordStatus.ACTIVE }) status!: RecordStatus; @ManyToOne(() => DsaPartner) @JoinColumn({ name: 'partner_id' }) partner!: DsaPartner; }
@Entity('commission_rules') export class CommissionRule extends SoftDeleteEntity { @Column({ length: 160 }) name!: string; @Column({ name: 'partner_id', type: 'char', length: 36, nullable: true }) partnerId?: string; @Column({ name: 'product_id', type: 'char', length: 36, nullable: true }) productId?: string; @Column({ name: 'lender_id', type: 'char', length: 36, nullable: true }) lenderId?: string; @Column({ name: 'payout_percent', type: 'decimal', precision: 7, scale: 4 }) payoutPercent!: string; @Column({ type: 'json', nullable: true }) criteria?: Record<string, unknown>; @Column({ type: 'enum', enum: RecordStatus, default: RecordStatus.ACTIVE }) status!: RecordStatus; }
@Entity('commissions') export class Commission extends UuidEntity { @Unique(['disbursementId']) @Column({ name: 'disbursement_id', type: 'char', length: 36 }) disbursementId!: string; @Column({ name: 'rule_id', type: 'char', length: 36, nullable: true }) ruleId?: string; @Column({ name: 'gross_amount', type: 'decimal', precision: 15, scale: 2 }) grossAmount!: string; @Column({ name: 'tds_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) tdsAmount!: string; @Column({ name: 'deduction_amount', type: 'decimal', precision: 15, scale: 2, default: 0 }) deductionAmount!: string; @Column({ name: 'net_amount', type: 'decimal', precision: 15, scale: 2 }) netAmount!: string; @Column({ type: 'enum', enum: PaymentStatus, default: PaymentStatus.PENDING }) status!: PaymentStatus; @ManyToOne(() => Disbursement) @JoinColumn({ name: 'disbursement_id' }) disbursement!: Disbursement; }
@Entity('payouts') export class Payout extends UuidEntity { @Index({ unique: true }) @Column({ name: 'business_id', length: 30 }) businessId!: string; @Column({ name: 'commission_id', type: 'char', length: 36 }) commissionId!: string; @Column({ name: 'partner_id', type: 'char', length: 36, nullable: true }) partnerId?: string; @Column({ name: 'amount', type: 'decimal', precision: 15, scale: 2 }) amount!: string; @Column({ name: 'paid_at', type: 'datetime', nullable: true }) paidAt?: Date; @Column({ name: 'payment_reference', length: 120, nullable: true }) paymentReference?: string; @Column({ type: 'enum', enum: PaymentStatus, default: PaymentStatus.PENDING }) status!: PaymentStatus; }
@Entity('business_id_sequences') export class BusinessIdSequence extends UuidEntity { @Index({ unique: true }) @Column({ length: 40 }) scope!: string; @Column({ name: 'last_value', type: 'bigint', unsigned: true, default: 0 }) lastValue!: string; }
