import bcrypt from 'bcrypt';
import { AppDataSource } from '../config/data-source';
import { env } from '../config/env';
import { Permission, Role, RolePermission, User, UserRole } from '../entities/access.entities';
import { Lender, LenderProduct, LeadSource, LoanProduct, ProductPolicy } from '../entities/crm.entities';
import { CommissionRule } from '../entities/work-finance.entities';
import { ProductCategory } from '../constants/enums';
const roles = ['super_admin', 'business_head', 'sales_manager', 'sales_executive', 'credit_operations', 'legal_technical', 'accounts', 'channel_partner'];
const permissions = ['users.view', 'users.manage', 'roles.view', 'roles.manage', 'customers.view', 'customers.create', 'customers.update', 'customers.delete', 'leads.view', 'leads.create', 'leads.update', 'leads.assign', 'applications.view', 'applications.create', 'applications.update', 'products.manage', 'lenders.manage', 'documents.verify', 'sanctions.approve', 'disbursements.manage', 'payouts.manage', 'reports.view', 'audit.view'];
async function seed() { await AppDataSource.initialize(); await AppDataSource.transaction(async manager => { const roleRepository = manager.getRepository(Role); const permissionRepository = manager.getRepository(Permission); for (const code of roles) await roleRepository.upsert({ code, name: code.split('_').map(part => part[0].toUpperCase() + part.slice(1)).join(' ') }, ['code']); for (const code of permissions) { const [module] = code.split('.'); await permissionRepository.upsert({ code, module, name: code }, ['code']); } const adminRole = await roleRepository.findOneByOrFail({ code: 'super_admin' }); const allPermissions = await permissionRepository.find(); for (const permission of allPermissions) await manager.createQueryBuilder().insert().into(RolePermission).values({ roleId: adminRole.id, permissionId: permission.id }).orIgnore().execute(); const passwordHash = await bcrypt.hash(env.SEED_ADMIN_PASSWORD, 12); await manager.getRepository(User).upsert({ email: env.SEED_ADMIN_EMAIL, passwordHash, firstName: 'Kuvik', lastName: 'Administrator' }, ['email']); const admin = await manager.getRepository(User).findOneByOrFail({ email: env.SEED_ADMIN_EMAIL }); await manager.createQueryBuilder().insert().into(UserRole).values({ userId: admin.id, roleId: adminRole.id }).orIgnore().execute(); const products = [{ code: 'PERSONAL_LOAN', name: 'Personal Loan', category: ProductCategory.RETAIL }, { code: 'HOME_LOAN', name: 'Home Loan', category: ProductCategory.RETAIL }, { code: 'LAP', name: 'Loan Against Property', category: ProductCategory.RETAIL }, { code: 'BUSINESS_LOAN', name: 'Business Loan', category: ProductCategory.BUSINESS }]; for (const product of products) await manager.getRepository(LoanProduct).upsert(product, ['code']); const sources = ['Website', 'WhatsApp', 'Facebook', 'Google', 'Telecalling', 'DSA', 'Referral', 'Branch', 'Existing Customer']; for (const name of sources) await manager.getRepository(LeadSource).upsert({ name }, ['name']); await manager.getRepository(Lender).upsert({ businessId: 'KUV-LENDER-000001', code: 'DEMO_BANK', name: 'Demo Bank' }, ['code']); const lender = await manager.getRepository(Lender).findOneByOrFail({ code: 'DEMO_BANK' }); const personalLoan = await manager.getRepository(LoanProduct).findOneByOrFail({ code: 'PERSONAL_LOAN' }); await manager.createQueryBuilder().insert().into(LenderProduct).values({ lenderId: lender.id, productId: personalLoan.id }).orIgnore().execute(); const mapping = await manager.getRepository(LenderProduct).findOneByOrFail({ lenderId: lender.id, productId: personalLoan.id }); await manager.getRepository(ProductPolicy).upsert({ lenderProductId: mapping.id, name: 'Default Personal Loan Policy', rules: { minCreditScore: 650, minMonthlyIncome: 25000 } }, ['lenderProductId', 'name']); await manager.getRepository(CommissionRule).upsert({ name: 'Default DSA Commission', payoutPercent: '1.0000' }, ['name']); }); await AppDataSource.destroy(); console.info('Development seed completed.'); }
seed().catch((error: unknown) => { console.error(error); process.exit(1); });
