import { Navigate, Outlet, Route, Routes } from 'react-router-dom';
import { AuthProvider, useAuth } from './context/AuthContext';
import { AppLayout } from './layouts/AppLayout';
import { DashboardPage, RolesPage, SettingsPage, UsersPage } from './pages/AdminPages';
import { ForgotPasswordPage, LoginPage, ResetPasswordPage } from './pages/AuthPages';
import { CustomerDetailPage, CustomersPage, EditCustomerPage, EditLeadPage, LeadDetailPage, LeadsPage, NewCustomerPage, NewLeadPage } from './pages/CrmPages';
import { EligibilityPage, LendersPage, NewLenderPage, NewProductPage, ProductsPage } from './pages/CatalogPages';
function Protected() { const { user, loading } = useAuth(); if (loading) return <main className="grid min-h-screen place-items-center">Loading…</main>; return user ? <Outlet /> : <Navigate to="/login" replace />; }
export default function App() { return <AuthProvider><Routes><Route path="/login" element={<LoginPage />} /><Route path="/forgot-password" element={<ForgotPasswordPage />} /><Route path="/reset-password" element={<ResetPasswordPage />} /><Route element={<Protected />}><Route element={<AppLayout />}><Route path="/dashboard" element={<DashboardPage />} /><Route path="/customers" element={<CustomersPage />} /><Route path="/customers/new" element={<NewCustomerPage />} /><Route path="/customers/:id/edit" element={<EditCustomerPage />} /><Route path="/customers/:id" element={<CustomerDetailPage />} /><Route path="/leads" element={<LeadsPage />} /><Route path="/leads/new" element={<NewLeadPage />} /><Route path="/leads/:id/edit" element={<EditLeadPage />} /><Route path="/leads/:id" element={<LeadDetailPage />} /><Route path="/products" element={<ProductsPage />} /><Route path="/products/new" element={<NewProductPage />} /><Route path="/lenders" element={<LendersPage />} /><Route path="/lenders/new" element={<NewLenderPage />} /><Route path="/eligibility" element={<EligibilityPage />} /><Route path="/users" element={<UsersPage />} /><Route path="/roles" element={<RolesPage />} /><Route path="/settings" element={<SettingsPage />} /></Route></Route><Route path="*" element={<Navigate to="/dashboard" replace />} /></Routes></AuthProvider>; }
